---
title: "Life_Of_Users"
author: "Gerardo Nunez"
date: "9/29/2017"
output: html_document
---


```{r setup include=FALSE, cache=TRUE}
start.time <- Sys.time()
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(RPostgreSQL)
library(dplyr)
library(dbplyr)
library(data.table)

  # Create a connection to Redshift database from the dplyr package

myRedshift <- src_postgres('dcmlogdata',
                           host = "dcm.cp1kfqsgbrzl.us-east-1.redshift.amazonaws.com",
                           port = 5439,
                           user = "ruser", 
                           password = "RUser2017")

  # Create tables
 
activity      <- tbl(myRedshift, "activity")

impression    <- tbl(myRedshift, "impression")

site          <- tbl(myRedshift, "site")

click         <- tbl(myRedshift, "click")

placement     <- tbl(myRedshift, "placement")
```

```{r Parameters, include=FALSE, cache=TRUE}

  # Virgin

adv.id <- 6417308

  # DBM

site.id <- 3635412

  # Conversion

conv.id <- 4302931

  # Start Date

start.date <- '07-01-2017'

  # End Date

end.date   <- '08-02-2017'

  # Top Bin

top.bin <- 35

  # Insertion Order

io.id <- 3536193

placement %>%
  count()

```

```{r FBX Audiences include=FALSE, cache=TRUE}

placement.info <- myRedshift %>% 
tbl(sql("SELECT
         placementid,
         placementname
         FROM
         placement
         WHERE
         placementname LIKE '%FBX%'"))

activity.users <- activity %>%
  select(userid,
         placementid)      %>%
  filter(userid != 0)      %>%
  select(userid,
         placementid)
  
impression.users <- impression %>%
  select(userid,
         placementid)          %>%
  filter(userid != 0)          %>%
  select(userid,
         placementid)

if (FALSE) {
  
activity.placement <- inner_join(placement.info,
                                 activity.users,
                                 by = "placementid") %>%
                      distinct()                     %>%
                      collect()

write.csv(activity.placement, "FBX_users.csv")

}

```

