---
title: "Geocoding Google Maps API"
author: "Marianne Rochet"
date: "1/15/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Geocode from R

Use Google Maps API to pull lat and long from an address.
Limitation: 2,500 calls a day


```{r Store file}

library(dplyr)

stores <- read.csv("~/R/Projects/R-DCM/Data Share (Only Data in the folder)/store.csv")

stores <- stores %>% 
  select(unique.identifier, address=addresses)

  
# If needed:
# stores <- stores %>% 
#  mutate(address=paste(ADDRESS_LN1, ADDRESS_CITY, ADDRESS_STATE, ADDRESS_ZIP, sep=", "))

```


```{r Geocode stores}

#install.packages("RCurl")
#install.packages("RJSONIO")
#install.packages("plyr")

library(RCurl)
library(RJSONIO)
library(plyr)

url <- function(address, return.call = "json", sensor = "false") {
 root <- "http://maps.google.com/maps/api/geocode/"
 u <- paste(root, return.call, "?address=", address, "&sensor=", sensor, sep = "")
 return(URLencode(u))
}

geoCode <- function(address,verbose=FALSE) {
 if(verbose) cat(address,"\n")
 u <- url(address)
 doc <- getURL(u)
 x <- fromJSON(doc,simplify = FALSE)
 if(x$status=="OK") {
 lat <- x$results[[1]]$geometry$location$lat
 lng <- x$results[[1]]$geometry$location$lng
 location_type <- x$results[[1]]$geometry$location_type
 formatted_address <- x$results[[1]]$formatted_address
 return(c(lat, lng, location_type, formatted_address))
 } else {
 return(c(NA,NA,NA, NA))
 }
}

locations <- ldply(stores$address, function(x) geoCode(x))

detach(package:plyr)

library(dplyr)

locations <- locations %>% 
  select(lat=V1, lng=V2, location_type=V3, formatted_address=V4)

locations2 <- cbind(locations, stores) 

locations2 <- locations2[!is.na(locations2["lng"]),] 

```


```{r Append DMA}
install.packages("rgeos")
install.packages("rgdal")
install.packages("maptools")
install.packages("shapefiles")
install.packages("raster")

library(rgeos)
library(rgdal)
library(maptools)
library(shapefiles)
library(raster)
library(dplyr)

s <- shapefile("~/R/Projects/R-DCM/Drivers/usdmas/usdmas.shp")
xy <- locations2[1:2]
xy <- xy[complete.cases(xy),]
xy <- lapply(xy, as.numeric)
xy <- as.data.frame(xy)
coordinates(xy) <- ~V2+V1 # Identify X Y as Lat long
proj4string(xy) <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")
xyz <- extract(s, xy)

dma_name <- as.data.frame(s[,c("Name","Key")])

complete<- cbind(locations2, xyz)
names(complete)
#complete <- complete[, names(complete) != "DMA_CODE"]
#complete2<- merge(complete, dma_name2, by=c("Key"), x.all=TRUE)

```

```{r Region mapping}

install.packages("ggplot2")
install.packages("ggmap")
#install.packages("mapdata")
install.packages("RColorBrewer")
install.packages("fiftystater")

library(dplyr)
library(tidyr)
library(ggplot2)
#library(ggmap)
library(maps)
library(mapdata)

library(RColorBrewer)

library(fiftystater)

county_region <- read.csv("/home/mariannerochet/R/Git_Projects/R-DCM/Generic/Assets/Inputs/County Region.csv")
state_ref <- read.csv("/home/mariannerochet/R/Git_Projects/R-DCM/Generic/Assets/Inputs/STATES.csv")
county_regionNA <- read.csv("/home/mariannerochet/R/Git_Projects/R-DCM/Generic/Assets/Inputs/NA.csv")


usa <- map_data("usa")
states <- map_data("state")
counties <- map_data("county")

fifty_states <- map_data("fifty_states") 

state_ref <- state_ref %>% 
  mutate(region=tolower(STATENAME))

states <- states %>% 
  left_join(state_ref,by="region")

AK_HI <- data.frame("state"=c("alaska","hawaii"),REGION=c("NORTHWEST","NORTHWEST"))

AK_HI2 <- AK_HI %>% 
  select(id=state) %>% 
  left_join(fifty_states, by="id") 

AK_HI_names <-  aggregate(cbind(long, lat) ~ id, data=AK_HI2, FUN=function(x)min(range(x))+1) %>% 
  select(region=id, lat, long) %>% 
  left_join(state_ref, by="region")


statesnames <-  aggregate(cbind(long, lat) ~ STATE, data=states, FUN=function(x)mean(range(x)))

county_region2 <- county_region %>% 
  select(COUNTY=County,everything()) %>% 
  separate(COUNTY,c("STATE","County"), sep = ":", remove=FALSE) %>%
  left_join(state_ref, by="STATE") %>% 
  left_join(county_regionNA, by=c("STATE","County")) %>% 
  mutate(County=ifelse(is.na(County2),tolower(County),as.character(County2)),State=ifelse(is.na(State2),tolower(STATENAME),as.character(State2)), NissanRegion=ifelse(is.na(NissanRegion),as.character(Region),as.character(NissanRegion))) %>% 
  select(subregion=County,region=State,NissanRegion) 

county_region2 <- counties %>% 
  left_join(county_region2, by=c("region","subregion")) %>% 
  mutate(NissanRegion=ifelse(subregion=="shannon" & region=="south dakota","MOUNTAIN",NissanRegion)) %>% 
  select(REGION=NissanRegion, everything())

#Add State names, add Alaska and Hawai + Legend + change color

display.brewer.all()

ggplot() + 
  geom_polygon(data = county_region2,aes(x = long, y = lat, fill = REGION, group = group)) + 
  coord_fixed(1.3) +
  scale_fill_brewer(palette="Set2") +
  geom_polygon(data = states,aes(x = long, y = lat, fill = region, group = group), fill = NA, color = "white") + 
  coord_fixed(1.3) +
  geom_text(data = statesnames, aes(long, lat, label = STATE),
                    color = "white", size=3, fontface="bold") + 
  theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      #legend.position="none",
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank())


ggplot() + 
  geom_polygon(data = county_region2,aes(x = long, y = lat, fill = REGION, group = group)) + 
  coord_fixed(1.3) +
  scale_fill_brewer(palette="Set2") +
  geom_polygon(data = states,aes(x = long, y = lat, fill = region, group = group), fill = NA, color = "white") + 
  coord_fixed(1.3) +
  geom_text(data = statesnames, aes(long, lat, label = STATE),
                    color = "white", size=3, fontface="bold") +
  geom_map(data = AK_HI, aes(map_id = state, fill = REGION), map = fifty_states) +
  geom_text(data = AK_HI_names, aes(long, lat, label = STATE),
                    color = "grey30", size=3, fontface="bold") +
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() + 
  fifty_states_inset_boxes() + 
  ggtitle("2017 NISSAN REGIONS") +
  theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      #legend.position="none",
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank(),
      plot.title = element_text(family = "Trebuchet MS", color="grey30", face="bold", size=18, hjust=0.5),
      legend.text = element_text(family = "Trebuchet MS", color="grey30", size=9),
      legend.title = element_text(family = "Trebuchet MS", color="grey30", face="bold", size=10))


ggsave("/home/mariannerochet/R/Git_Projects/R-DCM/Generic/Assets/Outputs/2017 Nissan Regions Map.png", width = 10, height = 7)

```