
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Package censusapi}

library(censusapi)

mycensuskey <- "df9e0036b1d36e28e6a40766e6f00e2ae4c6cee9"
myvintage <- 2016

availablegeos <- listCensusMetadata(name = "acs/acs5", vintage = myvintage,  type = "g")
availablevars <- listCensusMetadata(name = "acs/acs5", vintage = myvintage)

possible_vars <- subset(availablevars, grepl("gender", availablevars$label, ignore.case = TRUE))

data <- getCensus(name = "acs/acs5", vintage=myvintage, key=mycensuskey, vars = c("NAME", "B19013_001E", "B01002_001E", "B01003_001E","B01001_002E", "B01001_026E", "B02001_002E", "B02001_003E", "B02001_004E", "B02001_005E", "B02001_006E", "B02001_007E", "B02001_008E", "B07001_002E"), region = "zip code tabulation area:*")

colnames(data) <- c("Zip", "Zipcode", "Median Income", "Median Age", "Total Population", "Male Population", "Female Population", "Population-white", "Population-Black or African", "Population-Indian and Alaska Native", "Population-Asian", "Population-Hawaii", "Population-other race alone", "Population -2 or more race","1-4")

calcode <- median_incomes_us$state[median_incomes_us$NAME =="Florida"]

median_incomes_us <- getCensus(name = "acs5", vintage=myvintage, key=mycensuskey, vars = c("NAME", "B19013_001E", "C02003_009E"), region = "zip code tabulation area:*")


write.csv(data, "Z:/Media/Media/INTERACTIVE/Personal Folders/Doris Sun/US Census/ACS5/dataexport.csv", row.names = FALSE)
                                
```